# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Gourab Panigrahi
title: PhD Student
email: pgourab@iisc.ac.in
website: https://gourabp7.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  gourabp7
# stackoverflow_username: "pgourab"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: gourab.7777
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0001-8121-3320

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Gourab and I'm a PhD Student at the Department of Computational Data Sciences, Indian Institute of Science, Bangalore. My research focusses on developing hardware-aware computational algorithms and
  novel implementation procedures that can further accelerate quantum modeling of materials on extreme-scaling computing architectures using Finite Element discretization of Kohn-Sham Density Functional Theory equations.

  I am most skilled in: <mark>CUDA C/C++</mark>, <mark>C/C++</mark>, <mark>OpenMPI</mark> and <mark>Python</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: DFT-FE
        link: github.com/dftfeDevelopers/dftfe
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          2019 ACM Gordon Bell Prize Finalist, the highest prize in Scientific Computing.
        description: | # this will include new lines to allow paragraphs
          Contributor to DFT-FE (C++/CUDA/MPI), a massively parallel finite-element based open-source code for material modeling using density functional theory (DFT). DFT-FE can handle periodic, non-periodic and semi-periodic calculations. It can further handle both pseudopotential (ONCV, Troullier-Martins) and all-electron (non-relativistic) calculations; XC functionals supported are LDA, GGA (including spin-polarized); Capabilities include ground-state calculations, structural relaxations (ionic, cell), ab-initio MD (NVE). Scalability tested on ~200,000 MPI tasks on many-core architectures and ~24,000 GPUs on hybrid CPU-GPU architectures.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: MATRIX Lab, Computational Data Sciences, IISc
        link: https://sites.google.com/view/matrix-lab/research
        # link_text: boringcompany.com
        sub_title: Project Associate
        caption: September 2020 - August 2021
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Developing hardware-aware computational algorithms based on the matrix-free paradigm to evaluate on-the-fly finite-element discretized matrix-multivector products arising in solving the DFT problem without
            storing the cell-level matrices or the global sparse matrix.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Indian Institute of Science
        caption: 2014 - 2018
        sub_title: Bachelor of Science (Research) in Physics
        quote: >
          Established in 1909, IISc is India’s premier institute for advanced scientific and technological research and education. In 2018, IISc was selected as an Institution of Eminence (IoE) by the Government of India, and it consistently figures among the top Indian institutions in world university rankings.
        description: | # this will include new lines to allow paragraphs
          In my Bachelors Thesis titled "Orbital Effect of Magnetic Field on a Current Driven System" under Prof. Sumilan Banerjee, I studied Non-Hermitian PT-Symmetric quantum hamiltonian models used to describe nonequilibrium steady states of dissipative quantum systems.

      - layout: left
        title: Indian Institute of Science
        caption: 2018 - 2019
        sub_title: Master of Science in Physics
        # quote: >
        #   Established in 1909, IISc is India’s premier institute for advanced scientific and technological research and education. In 2018, IISc was selected as an Institution of Eminence (IoE) by the Government of India, and it consistently figures among the top Indian institutions in world university rankings.
        description: | # this will include new lines to allow paragraphs
          In my Masters Thesis titled "Time-dependent Density Functional Theory" under Prof. Manish Jain, I worked with implementating a time-dependent density functional theory module in anin-house python port of quantum espresso and applying it to study the response or the induced polarization when a time-dependent electric field is applied to a system.

    Comment: >
          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computer hardware some of my other interests and hobbies are:
      - Trekking
      - Photography
    Comment: >
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
